### ISSUE TITLE
axios问题

### ISSUE THREAD

**Issue by shellus** [imsole/project-template#1]
https://github.com/imsole/project-template/blob/cffc452e4090796739335640d6557fdb5f87117e/src/libs/http.js#L134-L138

上面几行代码中，如果是post方法，并且需要附带 params，就无法处理了。所以这个fetch方法封装有问题，基本可用性都没有达到

**Comment by imsole** [comment]
如果你想，可以吧参数改为一个Object对象，像下面这样
```js
const fetch = async (options) => {
    let args = {...options};

    if (/\{(\w+)\}/.test(args.url)) {
        var res = args.url.match(/\{(\w+)\}/);
        args.url = args.url.replace(/\{(\w+)\}/, data[res[1]]);
        delete data[res[1]];
    }

    args.method = args.method || 'GET';

    return service(args);
}
```
get和post同时存在情况毕竟很少；
既然都用post了，为什么不把参数都进行post提交呢；
如果可以get请求的参数你可以直接放到url里面，也是没问题的啊；
一个项目也不可能每一个接口都会设计成get和post同时存在的情况吧；
可用性有没有达到也是看项目的，我这个也不代表全网，所以嘛认真你就输了😂
